# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:

services:
    star_rating.type:
        class: blackknight467\StarRatingBundle\Form\RatingType
        tags:
            - { name: form.type, alias: rating }

    star_rating.twig:
        class: blackknight467\StarRatingBundle\Extensions\StarRatingExtension
        tags: [{ name: twig.extension }]
        arguments:
            - '@service_container'
